import "../styles/global.css";

export const metadata = {
  title: "Billionaires",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <div className="layout">{children}</div>
      </body>
    </html>
  );
}
